build(SF-1061): Replace re-start with custom release scripts
groupby/storefront-details pull request #32
Opened 2018-10-23 18:45 UTC by jmbtutor

2018-10-24 15:37 UTC, Vic-Dev requested changes
Some minor things

2018-10-24 15:37 UTC, Vic-Dev commented on .circleci/config.yml
> +          name: Setup Git user
Do we need this? Remove

2018-10-24 15:37 UTC, Vic-Dev commented on CONTRIBUTING.md
> +### Changed
Added | Changed | Deprecated | Removed | Fixed | Security

2018-10-24 15:37 UTC, Vic-Dev commented on CONTRIBUTING.md
> +Our CHANGELOG.md follows the [Keep a Changelog](https://keepachangelog.com) format. For every change add an Unreleased section by copying this format and adding it to the top of the CHANGELOG.md:
Describe how modifying the CHANGELOG triggers the release

2018-10-24 15:37 UTC, Vic-Dev commented on scripts/publish.sh
> +Publishes the current package to npm.
`based on the version in package.json`

2018-10-24 15:37 UTC, Vic-Dev commented on scripts/release.sh
> +
Add shebang at the top

2018-10-24 15:37 UTC, Vic-Dev commented on scripts/release.sh
> +    die "Could not detect potential release in the CHANGELOG."
Add exit code

2018-10-24 15:37 UTC, Vic-Dev commented on scripts/release.sh
> +    die "Unsupported release type: ${release_type}"
Add exit code

2018-10-24 15:37 UTC, Vic-Dev commented on scripts/release.sh
> +sed -n '/## \[/,//p' CHANGELOG.md | sed -e '$d' -e 's/^##* *//' -e $'1a\\\n\\\n' |
See if you can combine these seds

2018-10-24 19:41 UTC, JoeyDeol commented on scripts/release.sh
> +sed -n '/## \[/,//p' CHANGELOG.md | sed -e '$d' -e 's/^##* *//' -e $'1a\\\n\\\n' |
Decided to leave unchanged for clarity.

2018-10-25 14:30 UTC, Vic-Dev commented on CONTRIBUTING.md
> +The release type corresponds to the arugement to `npm version`.
`argument`. Also mention specifically somewhere that the update to the CHANGELOG.md is what triggers the release

2018-10-25 14:32 UTC, Vic-Dev requested changes
One more thing

2018-10-25 14:32 UTC, Vic-Dev commented on CONTRIBUTING.md
> +The release type corresponds to the arugement to `npm version`.
`argument`. Also mention specifically somewhere that the update to the CHANGELOG.md is what triggers the release

2018-10-25 14:54 UTC, Vic-Dev approved these changes

2018-10-25 14:58 UTC, merged